dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/pipenv"
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
- (cd manager && pipenv install --dev --deploy)
- (cd orchestrator && pipenv install --dev --deploy)
- (cd router && pipenv install --dev --deploy)
script:
- (cd manager && pipenv run ./scripts/format.sh)
- (cd manager && pipenv run ./scripts/static_templates_format.sh)
- (cd manager && test -z "$(git status --porcelain=v1 .)")  # If this fails, you forgot to run scripts/format.sh or scripts/static_templates_format.sh
- (cd manager && pipenv run ./scripts/check.sh)
- (cd orchestrator && pipenv run ./scripts/format.sh)
- (cd orchestrator && test -z "$(git status --porcelain=v1 .)")  # If this fails, you forgot to run scripts/format.sh
- (cd orchestrator && pipenv run ./scripts/check.sh)
- (cd router && pipenv run ./scripts/format.sh)
- (cd router && test -z "$(git status --porcelain=v1 .)")  # If this fails, you forgot to run scripts/format.sh
- (cd router && pipenv run ./scripts/check.sh)
