dist: bionic
language: python
python:
- '3.6'
- '3.7'
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/pipenv"
  - "$HOME/.local/share/virtualenvs"
install:
- pip install -U pip setuptools pipenv
- (cd manager && pipenv install --dev --deploy)
- (cd orchestrator && pipenv install --dev --deploy)
script:
- (cd manager && pipenv run ./scripts/format.sh)
- (cd manager && test -z "$(git status --porcelain=v1 .)")  # If this fails, you forgot to run scripts/format.sh
- (cd manager && pipenv run ./scripts/check.sh)
- (cd orchestrator && pipenv run ./scripts/format.sh)
- (cd orchestrator && test -z "$(git status --porcelain=v1 .)")  # If this fails, you forgot to run scripts/format.sh
- (cd orchestrator && pipenv run ./scripts/check.sh)
